### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by tramdeholl** [jianyuan/terraform-provider-sentry#151]
I'm experiencing an issue with v0.8 release. This is not happening with v0.7.

```
Stack trace from the terraform-provider-sentry_v0.8.0 plugin:

panic: runtime error: index out of range [-1]

goroutine 98 [running]:
github.com/jianyuan/go-sentry/sentry.(*ProjectKeyService).listPerPage(0xc000620020, {0xc000046720, 0xc}, {0xc000046738, 0x8}, {0x0, 0x0})
github.com/jianyuan/go-sentry@v1.4.0/sentry/project_keys.go:73 +0x8da
github.com/jianyuan/go-sentry/sentry.(*ProjectKeyService).List(0xd30a40?, {0xc000046720?, 0xc1ecb2?}, {0xc000046738?, 0xc0000fced0?})
github.com/jianyuan/go-sentry@v1.4.0/sentry/project_keys.go:60 +0x29
github.com/jianyuan/terraform-provider-sentry/sentry.dataSourceSentryKeyRead({0xd30a40, 0xc00013cc00}, 0x7fdbfdd9cf18?, {0xaebce0?, 0xc000622000})
github.com/jianyuan/terraform-provider-sentry/sentry/data_source_sentry_key.go:92 +0x298
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000258ee0, {0xd30a78, 0xc000511680}, 0xd?, {0xaebce0, 0xc000622000})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000258ee0, {0xd30a78, 0xc000511680}, 0xc000295180, {0xaebce0, 0xc000622000})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003c6420, {0xd309d0?, 0xc0000b8d00?}, 0xc000425ce0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000276aa0, {0xd30a78?, 0xc0005110e0?}, 0xc0000acff0)
github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:657 +0x409
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xbe3200?, 0xc000276aa0}, {0xd30a78, 0xc0005110e0}, 0xc00013c1e0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023c8c0, {0xd33490, 0xc0003f01a0}, 0xc00024fe60, 0xc0003d62a0, 0x119f7b0, 0x0)
google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc00023c8c0, {0xd33490, 0xc0003f01a0}, 0xc00024fe60, 0x0)
google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

Error: The terraform-provider-sentry_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

![image](https://user-images.githubusercontent.com/82117396/172689624-494f1d43-803b-466f-bccf-40425dc00d54.png)

**Comment by jianyuan** [comment]
This should be fixed in the upcoming release (v0.9.0).
