### ISSUE TITLE
Plugin Crashed

### ISSUE THREAD

**Issue by MohammadFebriyanto** [jianyuan/terraform-provider-sentry#232]
Hi, I got this error when initiate sentry configuration in terraform.

```
Error: Request cancelled

  with data.sentry_organization.main,
  on data.tf line 5, in data "sentry_organization" "main":
   5: data "sentry_organization" "main" {

The plugin.(*GRPCProvider).ReadDataSource request was cancelled.

Stack trace from the terraform-provider-sentry_v0.10.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xabac69]

goroutine 41 [running]:
github.com/jianyuan/go-sentry/v2/sentry.CheckResponse(0xbafb20?)
	github.com/jianyuan/go-sentry/v2@v2.0.0/sentry/sentry.go:343 +0x29
github.com/jianyuan/terraform-provider-sentry/sentry.(*Config).Client.func1(0xd86190?, 0xc000124000?, 0x15?, 0xd81ec0?)
	github.com/jianyuan/terraform-provider-sentry/sentry/config.go:39 +0x30
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000160540, 0xc0000111b8)
	github.com/hashicorp/go-retryablehttp@v0.7.1/client.go:673 +0xd37
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc000010810, 0x0?)
	github.com/hashicorp/go-retryablehttp@v0.7.1/roundtripper.go:44 +0x7d
github.com/jianyuan/terraform-provider-sentry/sentry.(*semaphoreTransport).RoundTrip(0xc0003bf6e0, 0xc0000ac800)
	github.com/jianyuan/terraform-provider-sentry/sentry/config.go:83 +0x20f
net/http.send(0xc0000ac800, {0xd80bc0, 0xc0003bf6e0}, {0xc3d1e0?, 0x1?, 0x0?})
	net/http/client.go:251 +0x5f7
net/http.(*Client).send(0xc0003bf740, 0xc0000ac800, {0x40d5bf?, 0xc000472000?, 0x0?})
	net/http/client.go:175 +0x9b
net/http.(*Client).do(0xc0003bf740, 0xc0000ac800)
	net/http/client.go:715 +0x8fc
net/http.(*Client).Do(...)
	net/http/client.go:581
github.com/jianyuan/go-sentry/v2/sentry.(*Client).BareDo(0x0?, {0xd861c8, 0xc0000c2fc0}, 0xc00004ac00?)
	github.com/jianyuan/go-sentry/v2@v2.0.0/sentry/sentry.go:242 +0x45
github.com/jianyuan/go-sentry/v2/sentry.(*Client).Do(0xc000127680?, {0xd861c8?, 0xc0000c2fc0?}, 0xc00003cb40?, {0xb28520?, 0xc00016e840})
	github.com/jianyuan/go-sentry/v2@v2.0.0/sentry/sentry.go:260 +0x79
github.com/jianyuan/go-sentry/v2/sentry.(*OrganizationsService).Get(0xc0001276a0, {0xd861c8, 0xc0000c2fc0}, {0xc000044e70?, 0xc00045d2f8?})
	github.com/jianyuan/go-sentry/v2@v2.0.0/sentry/organizations.go:108 +0xe5
github.com/jianyuan/terraform-provider-sentry/sentry.dataSourceSentryOrganizationRead({0xd861c8, 0xc0000c2fc0}, 0x0?, {0xb9a980?, 0xc000127680})
	github.com/jianyuan/terraform-provider-sentry/sentry/data_source_sentry_organization.go:45 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003da1c0, {0xd86200, 0xc0004a2810}, 0xd?, {0xb9a980, 0xc000127680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0003da1c0, {0xd86200, 0xc0004a2810}, 0xc000462780, {0xb9a980, 0xc000127680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003abdb8, {0xd86200?, 0xc0004a26f0?}, 0xc00007c8a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc00026f680, {0xd86200?, 0xc000091740?}, 0xc00043afa0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:658 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0xc28ce0?, 0xc00026f680}, {0xd86200, 0xc000091740}, 0xc0001608c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001dc1e0, {0xd89c00, 0xc0003e6340}, 0xc000465e60, 0xc0003bf5f0, 0x121e090, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001dc1e0, {0xd89c00, 0xc0003e6340}, 0xc000465e60, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-sentry_v0.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

This is my code.
```
# providers.tf
provider "sentry" {
  token    = "mytoken"
  base_url = "my-url/api/"
}


# data.tf
data "sentry_organization" "main" {
  slug = "sentry"
}

# versions.tf
terraform {
  required_providers {
    sentry = {
      source  = "jianyuan/sentry"
      version = "0.10.0"
    }
  }
}
```

**Comment by MohammadFebriyanto** [comment]
No problem, just an issue with my firewall, so the backend can't reach the sentry host.
