### ISSUE TITLE
Provider crash

### ISSUE THREAD

**Issue by tomaspinho** [jianyuan/terraform-provider-sentry#279]
Hello! Thank you so much for maintaining this provider.

Since today, we have this crash every time we run a `terraform plan` . We have made no changes to our Terraform code since it was last working.

```
Stack trace from the terraform-provider-sentry_v0.11.2 plugin:

panic: runtime error: index out of range [3] with length 3

goroutine 54 [running]:
github.com/jianyuan/terraform-provider-sentry/sentry.followShape({0xb3e080?, 0xc0008398d8?}, {0xb3e080?, 0xc000839920?})
	github.com/jianyuan/terraform-provider-sentry/sentry/helpers.go:79 +0x405
github.com/jianyuan/terraform-provider-sentry/sentry.resourceSentryIssueAlertRead({0xd8cf48, 0xc0000ba1e0}, 0xc00028d100, {0xb9ea40?, 0xc0002a0320})
	github.com/jianyuan/terraform-provider-sentry/sentry/resource_sentry_issue_alert.go:226 +0x79c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000240d20, {0xd8cf80, 0xc0001fdf20}, 0xd?, {0xb9ea40, 0xc0002a0320})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000240d20, {0xd8cf80, 0xc0001fdf20}, 0xc0002a2820, {0xb9ea40, 0xc0002a0320})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000431dd0, {0xd8cf80?, 0xc0001fde00?}, 0xc000694fc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000279680, {0xd8cf80?, 0xc0001fd830?}, 0xc000614600)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc2cf00?, 0xc000279680}, {0xd8cf80, 0xc0001fd830}, 0xc0001a84d0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d21e0, {0xd90980, 0xc0004f8000}, 0xc0005e1320, 0xc00043fb60, 0x12280d0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001d21e0, {0xd90980, 0xc0004f8000}, 0xc0005e1320, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-sentry_v0.11.2 plugin crashed!
```

**Comment by JaimeLennox** [comment]
We ran into this issue as well - seems to be caused by changing sentry directly instead of via the terraform provider. We resolved this by undoing the manual changes in sentry, after which we could make them again in terraform instead.

**Comment by kseniyashaydurova** [comment]
We have the same problem now, can you please add a fix for it?

**Comment by tomaspinho** [comment]
Finally had some time to fix our sentry terraform code. This issue is caused by manual changes to filters in `issue_alerts`. If the list of filters changes number (a filter is removed, in my case), the provider crashes.

**Comment by tomaspinho** [comment]
The same issue also happens when managed resources are manually deleted outright - deleting an `issue_alert`.

**Comment by jianyuan** [comment]
v0.12.0 now uses JSON strings for defining `conditions`, `filters`, and `actions`. This runtime error should not crop up anymore. https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/issue_alert
