### ISSUE TITLE
Index out of range crash when modifying alerts

### ISSUE THREAD

**Issue by jonathroth** [jianyuan/terraform-provider-sentry#339]
Hi, I'm getting the following panic while running `terraform plan` after modifying an alert
Help appreciated :)
```
panic: runtime error: index out of range [11] with length 11

goroutine 59 [running]:
github.com/jianyuan/terraform-provider-sentry/sentry.followShape({0xb3e080?, 0xc00063df80?}, {0xb3e080?, 0xc00063dfc8?})
	github.com/jianyuan/terraform-provider-sentry/sentry/helpers.go:79 +0x405
github.com/jianyuan/terraform-provider-sentry/sentry.resourceSentryIssueAlertRead({0xd8cf48, 0xc0004c5ec0}, 0xc0004b5500, {0xb9ea40?, 0xc000129ea0})
	github.com/jianyuan/terraform-provider-sentry/sentry/resource_sentry_issue_alert.go:226 +0x79c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00009eb60, {0xd8cf80, 0xc000588420}, 0xd?, {0xb9ea40, 0xc000129ea0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:[724](https://github.com/zeroabstraction/infrastructure/actions/runs/7029436109/job/19127039427?pr=1071#step:12:725) +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00009eb60, {0xd8cf80, 0xc000588420}, 0xc0004a9860, {0xb9ea40, 0xc000129ea0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00039d260, {0xd8cf80?, 0xc000588300?}, 0xc000249000)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000001900, {0xd8cf80?, 0xc000521d10?}, 0xc0004c4ba0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc2cf00?, 0xc000001900}, {0xd8cf80, 0xc000521d10}, 0xc0001651f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003b4000, {0xd90980, 0xc0003c96c0}, 0xc0002a4240, 0xc0003c08a0, 0x12280d0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0003b4000, {0xd90980, 0xc0003c96c0}, 0xc0002a4240, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
```

**Comment by jianyuan** [comment]
v0.12.0 now uses JSON strings for defining `conditions`, `filters`, and `actions`. This runtime error should not crop up anymore. https://registry.terraform.io/providers/jianyuan/sentry/latest/docs/resources/issue_alert
